
server:
  port: 8088

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:EFFM00/config-server-ondemand-dh.git
          hostKeyAlgorithm: ssh-rsa
          privateKey: |
                      -----BEGIN RSA PRIVATE KEY-----
                      -----END RSA PRIVATE KEY-----